defenses against CAN attacks
nmfta-repo/vcr-experiment pull request #27
Opened 2022-04-26 21:30 UTC by BenGardiner

2022-05-04 11:58 UTC, kentindell requested changes
I think most of those requirements can be reduced to "don't allow CAN protocol attacks" **however** it is better to enumerate the known attacks to at least raise awareness.

I would add one more overarching requirement: to prevent CAN protocol attacks (defined as giving an attacker control of the RX and TX pins on a CAN transceiver connected to the TND). The reason is that there may be other CAN protocol attacks that emerge in the future and it would be better to catch them all now with one requirement rather than have to update this document as they emerge.

2022-05-04 15:15 UTC, jmaag15 commented
Reviewed, but will not merge until @kentindell's request has been discussed

2022-05-04 17:25 UTC, BenGardiner commented
agreed @kentindell , @jmaag15 . I've collected the CAN protocol attacks together into our model of a composite requirement in the latest

2022-05-04 17:36 UTC, BenGardiner commented
janus attack requirement now reflects group concensus 20220428 that janus attack should be expected on UND but not on TND

2022-05-04 17:36 UTC, kentindell commented
I'm good with those changes. One final question: the requirements as stated are for Janus and Address Claim attacks on UND. Does this mean:

1. That the gateway should detect and not pass through Janus frames, and
2. That the gateway should detect and frustrate the address claim attack?

(1) is a kind of IDS function. It's OK to require this, and I think it's implementable on a sufficiently good microcontroller.

(2) raises some issues. Right now, is the address claim protocol required to work through the security gateway? I don't understand it in enough detail yet but AIUI it exploits the CAN error passive mechanism to do a meta-arbitration. That means that the security gateway would have to try to replicate this across two separate buses, which is not just tricky (because there's a sync problem keeping both sides together) but also could constitute a flood attack on TND, stimulated by a device on UND.

2022-05-04 17:40 UTC, kentindell commented
> janus attack requirement now reflects group concensus 20220428 that janus attack should be expected on UND but not on TND

Yep, I'm good with this. When the CVE for the Janus attack is officially released (which is any day now) then maybe it's worth taking some of the mitigations in that bulletin into the ECU hardening requirements (like locking down the pin mux). That would then underpin this UND-only requirement.

2022-05-04 17:44 UTC, BenGardiner commented
@kentindell 
> 2\. That the gateway should detect and frustrate the address claim attack?

I think 
```
[REQUIREMENT]
UID: J1939GW-S-029
REFS:
- TYPE: Parent
  VALUE: AGW-S-002
TITLE: Prevents Address Claim Attacks
STATEMENT: The device SHALL prevent generating address claim attacks on *TND* from messages originating on *UND*. c.f. https://www.aut.upt.ro/~bgroza/Papers/j1939.pdf and https://doi.org/10.4271/02-14-03-0026 for a description of the address claim attack.
```

isn't in turn requiring detection or an active defense. e.g. if there is no address claim gatewaying then the requirement is trivially satisfied. In the case where gatewaying of address claim is a feature then tracking, rate limiting or something else is needed to prevent the attack on TND from UND.

2022-05-09 14:31 UTC, kentindell commented
Just one comment: "expected to be impervious to Janus Attacks since it should all be OEM supplied components there" holds only if there are mitigations to prevent an OEM device being hijacked (e.g. by diagnostic stack bug) and then carrying out a Janus (or other CAN protocol) attack on other devices.

Simple mitigations for this should be in place: sample points verified as confirming to J1939 (to defend against Janus), enabling of pin mux lock by secure bootloader or use of an external CAN controller (to mitigate carrying out of CAN protocol attacks).

2022-05-09 15:12 UTC, BenGardiner commented
> Just one comment: "expected to be impervious to Janus Attacks since it should all be OEM supplied components there" holds only if there are mitigations to prevent an OEM device being hijacked (e.g. by diagnostic stack bug) and then carrying out a Janus (or other CAN protocol) attack on other devices.

Not sure I agree, @kentindell. If all devices are impervious to reception of Janus frames (no devices will differ on their deserialization of any message sent) then even if a TND device is compromised and a Janus protocol level bitstream is sent the attack will not succeed because all nodes receive the same 'side' of the janus bitstream.

2022-05-09 15:59 UTC, kentindell commented
> Not sure I agree, @kentindell. If all devices are impervious to reception of Janus frames (no devices will differ on their deserialization of any message sent) then

Correct. But that requires that the ECUs are actually set up to be impervious. J1939 does specify a single sample point, but I can see how if it's not an overt security requirement to do so then it can get missed out: it's unlikely to show up in testing if someone just used 50% as the sample point.

I don't think this is a requirement for security gateways and it's out of scope here, but it should exist in an ECU security requirement document somewhere.

2022-05-09 16:12 UTC, BenGardiner commented
> Correct. But that requires that the ECUs are actually set up to be impervious.

Yep -- that's my point :) OK we're in violent agreement here 💯

2022-05-10 16:50 UTC, jmaag15 commented
Reviewed, reflects discussion on 20220505, merging

2022-05-10 16:51 UTC, merged